def decisionTree(x_train, x_test, y_train, y_test) 
dt DecisionTreeClassifier() 
dt.fit(x_train,y_train) 
yPred = dt.predict(x_test) 
print("***DecisionTreeClassifier****") 
print('Confusion matrix')
print(confusion_matrix(y_test,yPred)) 
print('Classification report') 
print(classification_report (y_test, yPred))